import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getDatabase, ref, onValue, set, get, push, remove, update } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js";

const firebaseConfig={apiKey:"AIzaSyBFpeuxnDSiuh65rlKtpxt0hLMXa2s00rw",authDomain:"match-predictions-17c35.firebaseapp.com",databaseURL:"https://match-predictions-17c35-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"match-predictions-17c35",storageBucket:"match-predictions-17c35.firebasestorage.app",messagingSenderId:"819779199942",appId:"1:819779199942:web:cfcd9c4f32c628346088c7"};
const app=initializeApp(firebaseConfig); const db=getDatabase(app);
const ADMIN_HASH="c738b7bf89988cc0cacac1b3ab3996e3a52a66e44ab6f01a61666721a0892e8c";
const DEFAULT_STATS={topScorers:[{name:"ليونيل ميسي",flag:"🇦🇷",goals:5},{name:"فينيسيوس جونيور",flag:"🇧🇷",goals:4},{name:"كيليان مبابي",flag:"🇫🇷",goals:4},{name:"إيرلينغ هالاند",flag:"🇳🇴",goals:4},{name:"دينيز أونداف",flag:"🇩🇪",goals:3}],goldenBall:[{name:"ليونيل ميسي",flag:"🇦🇷"},{name:"كيليان مبابي",flag:"🇫🇷"},{name:"مايكل أوليس",flag:"🇫🇷"},{name:"إيرلينغ هالاند",flag:"🇳🇴"},{name:"فينيسيوس جونيور",flag:"🇧🇷"}],updatedAt:0,updatedBy:"system"};
function $(id){return document.getElementById(id)}
function esc(s){return String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
async function sha256Hex(t){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(t));return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function adminName(){return localStorage.getItem("wc_admin_name")||"Admin"}
function logged(){return localStorage.getItem("wc_admin_ok")==="1"}
async function logAction(action,details={}){try{await push(ref(db,"adminLogs"),{action,details,admin:adminName(),time:Date.now(),ua:navigator.userAgent})}catch(e){console.warn(e)}}
function parseScorers(text){return text.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>{let p=line.split("|").map(v=>v.trim());return{name:p[0]||"",flag:p[1]||"",goals:Number(p[2]||0)}}).filter(x=>x.name).sort((a,b)=>b.goals-a.goals).slice(0,20)}
function parseGolden(text){return text.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>{let p=line.split("|").map(v=>v.trim());return{name:p[0]||"",flag:p[1]||""}}).filter(x=>x.name).slice(0,20)}
function scorersToText(a){return (a||[]).map(x=>`${x.name} | ${x.flag||""} | ${Number(x.goals||0)}`).join("\n")}
function goldenToText(a){return (a||[]).map(x=>`${x.name} | ${x.flag||""}`).join("\n")}
function renderStats(stats=DEFAULT_STATS){const s=(stats.topScorers&&stats.topScorers.length?stats.topScorers:DEFAULT_STATS.topScorers).slice().sort((a,b)=>(b.goals||0)-(a.goals||0)).slice(0,5);const g=(stats.goldenBall&&stats.goldenBall.length?stats.goldenBall:DEFAULT_STATS.goldenBall).slice(0,5);let se=$("topScorersList"),ge=$("goldenBallList"),upd=$("statsUpdated");if(se)se.innerHTML=s.map((x,i)=>`<div class="row"><div class="rank">${i+1}.</div><div class="name">${esc(x.name)} ${esc(x.flag||"")}</div><div class="score">⚽ ${Number(x.goals||0)}</div></div>`).join("");if(ge)ge.innerHTML=g.map((x,i)=>`<div class="row"><div class="rank">${i+1}.</div><div class="name">${esc(x.name)} ${esc(x.flag||"")}</div><div class="score">🏅</div></div>`).join("");if(upd)upd.textContent=stats.updatedAt?`آخر تحديث: ${new Date(stats.updatedAt).toLocaleString("ar-KW")} بواسطة ${stats.updatedBy||"Admin"}`:""}
function watchStats(){onValue(ref(db,"tournamentStats"),snap=>renderStats(snap.val()||DEFAULT_STATS),err=>{console.error(err);renderStats(DEFAULT_STATS)})}
async function loadAdminStats(){let snap=await get(ref(db,"tournamentStats"));let st=snap.val()||DEFAULT_STATS;if($("scorersText"))$("scorersText").value=scorersToText(st.topScorers||DEFAULT_STATS.topScorers);if($("goldenText"))$("goldenText").value=goldenToText(st.goldenBall||DEFAULT_STATS.goldenBall);renderStats(st)}
async function saveStats(){let topScorers=parseScorers($("scorersText").value);let goldenBall=parseGolden($("goldenText").value);let status=$("statsStatus");if(!topScorers.length||!goldenBall.length){status.innerHTML='<span class="bad">أدخل لاعب واحد على الأقل في كل قائمة.</span>';return}let before=(await get(ref(db,"tournamentStats"))).val()||null;let payload={topScorers,goldenBall,updatedAt:Date.now(),updatedBy:adminName()};await set(ref(db,"tournamentStats"),payload);await set(ref(db,"appConfig/tournamentStats"),payload);await logAction("save_tournament_stats",{before,after:payload});status.innerHTML='<span class="ok">✅ تم الحفظ في Firebase وتحديث الموقع مباشرة.</span>';renderStats(payload)}
async function exportBackup(){let paths=["tournamentStats","predictions","results","users","matches","adminLogs","appConfig"];let data={createdAt:new Date().toISOString(),data:{}};for(const p of paths){data.data[p]=(await get(ref(db,p))).val()||null}let blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});let url=URL.createObjectURL(blob);let a=document.createElement("a");a.href=url;a.download="wc2026-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(url);await logAction("export_backup",{})}
async function importBackup(file){let txt=await file.text();let backup=JSON.parse(txt);if(!backup.data)throw new Error("ملف غير صحيح");for(const [k,v] of Object.entries(backup.data)){if(["tournamentStats","predictions","results","users","matches","adminLogs","appConfig"].includes(k))await set(ref(db,k),v)}await logAction("import_backup",{keys:Object.keys(backup.data)});alert("تمت الاستعادة ✅")}
function renderLogs(){let el=$("logsBody");if(!el)return;onValue(ref(db,"adminLogs"),snap=>{let obj=snap.val()||{};let arr=Object.entries(obj).map(([id,v])=>({id,...v})).sort((a,b)=>(b.time||0)-(a.time||0)).slice(0,80);el.innerHTML=arr.map(x=>`<tr><td>${new Date(x.time||0).toLocaleString("ar-KW")}</td><td>${esc(x.admin||"")}</td><td><span class="pill">${esc(x.action||"")}</span></td><td>${esc(JSON.stringify(x.details||{})).slice(0,260)}</td></tr>`).join("")||'<tr><td colspan="4" class="muted">لا يوجد سجل حتى الآن</td></tr>'})}
function renderPredictionsAdmin(){let el=$("predictionsBody");if(!el)return;onValue(ref(db,"predictions"),snap=>{let obj=snap.val()||{};let rows=[];Object.entries(obj).forEach(([matchId,users])=>Object.entries(users||{}).forEach(([user,v])=>rows.push({matchId,user,...v})));rows.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));el.innerHTML=rows.slice(0,120).map(x=>`<tr><td>${esc(x.user)}</td><td>${esc(x.matchId)}</td><td>${esc(x.winner||x.prediction||"")}</td><td>${esc(x.byAdmin?"نعم":"لا")}</td><td><button class="btn red" data-del="${esc(x.matchId)}|${esc(x.user)}">حذف</button></td></tr>`).join("")||'<tr><td colspan="5" class="muted">لا توجد توقعات</td></tr>';el.querySelectorAll("[data-del]").forEach(btn=>btn.onclick=async()=>{let [m,u]=btn.dataset.del.split("|");let before=(await get(ref(db,`predictions/${m}/${u}`))).val();await remove(ref(db,`predictions/${m}/${u}`));await logAction("delete_prediction",{matchId:m,user:u,before})})})}
function setupAdmin(){let login=$("loginBox"),panel=$("adminPanel");if(logged()){login?.classList.add("hidden");panel?.classList.remove("hidden");loadAdminStats();renderLogs();renderPredictionsAdmin();return}login?.classList.remove("hidden");panel?.classList.add("hidden")}
window.wc={watchStats,saveStats,exportBackup,importBackup,setupAdmin,loadAdminStats,logAction};
window.addEventListener("DOMContentLoaded",()=>{if($("topScorersList"))watchStats();if($("adminPage")){setupAdmin();$("loginBtn").onclick=async()=>{let pass=$("adminPass").value;let name=$("adminName").value.trim()||"Admin";if(await sha256Hex(pass)===ADMIN_HASH){localStorage.setItem("wc_admin_ok","1");localStorage.setItem("wc_admin_name",name);await logAction("admin_login",{});setupAdmin()}else $("loginStatus").innerHTML='<span class="bad">الرمز غير صحيح</span>'};$("logoutBtn").onclick=()=>{localStorage.removeItem("wc_admin_ok");location.reload()};$("saveStatsBtn").onclick=saveStats;$("reloadStatsBtn").onclick=loadAdminStats;$("backupBtn").onclick=exportBackup;$("importFile").onchange=e=>{if(e.target.files[0])importBackup(e.target.files[0])}}});
